baseURL = 'https://siko-lang.github.io/'
languageCode = 'en-us'
title = 'Siko Programming Language'
theme = 'siko'

# Disable RSS feed generation and taxonomies
disableKinds = ['RSS', 'taxonomy', 'term']

[params]
  description = 'A blog about the Siko programming language'

[markup]
  [markup.highlight]
    style = 'vs'
    lineNos = true
    lineNumbersInTable = false
